spring:
  profiles:
    active: production
  cache:
    cache-names: vets
  cloud:
    config:
      uri: http://config-server-00001-private
  application:
    name: vets-service
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server.service-registry/eureka

